logging:
  level:
    ROOT: INFO
    ru.hotel.management: INFO

spring:
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: latest
      group-id: hotel-management
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
      client-id: hotel_store
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate
  application:
    name: hotel-management-control

# Http server port
server:
  port: 8081
